version: "3.8"

services:
  app:
    build:
      context: . # Build from current directory where Dockerfile is located
      dockerfile: Dockerfile # Specify which Dockerfile to use
    container_name: node_app
    working_dir: /usr/src/app # Set working directory inside container (optional since it's in Dockerfile)
    volumes:
      - .:/usr/src/app # Mount current directory to container for live updates during development
    ports:
      - "${PORT}:${PORT}" # Map port 3000 of host to port 3000 of container
    environment:
      - DB_HOST=db # Reference to database service name defined below
      - DB_USER=${DB_USER} # Database user for connection
      - DB_PASSWORD=${DB_PASSWORD} # Database password (should be secured in production)
      - DB_DATABASE=${DB_DATABASE} # Name of database to connect to
    depends_on:
      - db # Ensure db service starts before app service

  db:
    image: mariadb:latest # Use latest official MariaDB image
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD} # Root password for MariaDB
      MARIADB_DATABASE: ${DB_DATABASE} # Create new database on startup
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # Map port 3306 of host to port 3306 of container

networks:
  default:
    driver: bridge # Use bridge network for communication between containers
