apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts-configmap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
          id INT AUTO_INCREMENT PRIMARY KEY,
          content VARCHAR(255) NOT NULL,
          senderId INT NOT NULL,
          timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    )