apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer # Expose service externally (use ClusterIP for internal access only)
  ports:
    - port: 3000 # Port exposed by the service
      targetPort: 3000 # Port on which the container is listening 
  selector:
    app: node-app # Selector to link this service with its corresponding pods 