name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: mysql
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Compile Typescript to Javascript files
        run: npm run tsc-build

      - name: Build Docker image
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-typescript-demo:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-typescript-demo:latest

      - name: Run Docker image
        run: docker run -d -p 3000:3000 --name ${{ secrets.DOCKERHUB_USERNAME }}-nodejs-express-typescript-demo ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-express-typescript-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f node-deployment.yml
          kubectl apply -f node-service.yml
